//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int oid { get; set; }
        public Nullable<int> idmenu { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> priceamount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
